# Generated by Django 2.2.5 on 2019-09-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='shopping/image')),
                ('des', models.TextField()),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('Cust_Name', models.CharField(max_length=50)),
                ('Mobile_no', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Pub_Date', models.DateField()),
            ],
        ),
    ]
