# Generated by Django 2.2.5 on 2019-10-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Number', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Image', models.FileField(upload_to='student/image')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
