# Generated by Django 2.2.5 on 2019-10-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munna', '0002_auto_20191005_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('MiddleName', models.CharField(max_length=100)),
                ('SurName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('MobileNumber', models.CharField(max_length=50)),
                ('PublishDate', models.DateField()),
            ],
        ),
    ]
