# Generated by Django 2.2.5 on 2019-10-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munna', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('PublishDate', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('des', models.CharField(max_length=600)),
                ('image', models.FileField(upload_to='shopping/image')),
                ('aboutImage', models.CharField(max_length=600)),
            ],
        ),
    ]
