# Generated by Django 2.2.5 on 2019-10-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munna', '0004_cust'),
    ]

    operations = [
        migrations.CreateModel(
            name='tudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Address', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('dateTime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Cust',
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
