# Generated by Django 2.2.5 on 2019-10-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munna', '0005_auto_20191018_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('MobileNUmber', models.CharField(max_length=100)),
                ('ProductPublishDate', models.DateTimeField()),
                ('ProductType', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='tudent',
            name='Address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tudent',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
