# Generated by Django 2.2.5 on 2019-10-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munna', '0007_auto_20191018_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMag', models.ImageField(upload_to='')),
            ],
        ),
    ]
