# Generated by Django 2.2.5 on 2019-10-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('munna', '0009_auto_20191022_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hello',
            old_name='Moblie',
            new_name='Mobile',
        ),
    ]
