# Generated by Django 2.2.5 on 2019-10-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munna', '0010_auto_20191022_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Customer_Mobile_no', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=500)),
                ('Salary', models.CharField(max_length=100)),
            ],
        ),
    ]
