# Generated by Django 2.2.5 on 2019-10-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('munna', '0012_navbar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='image',
        ),
    ]
