# Generated by Django 2.2.5 on 2019-10-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('munna', '0013_remove_navbar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='Publish_Date',
        ),
    ]
