# Generated by Django 2.2.5 on 2019-10-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munna', '0014_remove_navbar_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tudent',
            name='image',
            field=models.ImageField(default=True, upload_to='image'),
        ),
    ]
