# Generated by Django 2.2.5 on 2019-10-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munna', '0015_tudent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tudent',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='tudent',
            name='email',
        ),
        migrations.AddField(
            model_name='tudent',
            name='dec',
            field=models.TextField(default=True),
        ),
    ]
